# Generated by Django 3.1.7 on 2021-03-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsF',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departments_f',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProductsF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_products_f',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersF',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_hour_of_day', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders_f',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsF',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('margin', models.FloatField()),
            ],
            options={
                'db_table': 'products_f',
                'managed': False,
            },
        ),
    ]
